services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always    # перезапуск без доп условий
    environment:
      - DATABASE_URL=sqlite:///./hackathon.db
      - SECRET_KEY=admin    # env прописал прямо тут
    ports:
      - "8000:8000"    # бэк открыт в сеть
    networks:
      - default    # отстутствует изоляция
    volumes:
      - ./backend:/app    # монтируем весь код
      - ./backend/files:/app/files
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always    # перезапуск без доп условий x2
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html    # весь фронт вмонтирован
    depends_on:
      - backend
    networks:
      - default    # отстутствует изоляция x2