name: bad CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Step 1
          uses: actions/checkout@v3

        - name: Step 2
          run: docker build -t static-site -f LabDocker/Dockerfile/Dockerfile.good .

        - name: Step 3
          run: | 
            docker run -d -p 8080:80 --name static static-site
            sleep 5
            curl --fail http://localhost:8080/landing/ChooseProject.html